### ISSUE TITLE
[Bug]: Adetailer being used before the roop extension

### ISSUE THREAD

**Issue by beped** [Bing-su/adetailer#193]
### Describe the bug

Here is the problem, I have adetailer and roop extensions installed but when run together, adetailer runs before and after roop comes on top. Therefore, the adetailer is useless on these occasions, as he adjusts the face and soon after roop enters on top of it, placing another face in the image, leaving it in low quality.
Is there any way to "force" the adetailer to always be the last one used?

### The entire console log, including python version information, webui version, commit hash, commandline arguments and error traces.

```Shell
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]                                 Version: v1.4.0                                                                                                         Commit hash: 394ffa7b0a7fff3ec484bcd084e673a8b301ccc8
```

### List of installed extensions

adetailer	https://github.com/Bing-su/adetailer.git	main	[5e4ac4af]	Wed Jul 5 15:21:53 2023

**Comment by Bing-su** [comment]
This solution will help you as well: https://github.com/Bing-su/adetailer/discussions/159

**Comment by bach777** [comment]
@Bing-su please, could you add an option that allows us to save the original inpanted area? let's say, I see in preview I get a very nice face in 768x768, then, I would like to use that same image in another upscaled version, the original inpanted image is 768x1024, but the face is shrunk... let's say 300x300px
So the original 768x768 image with all those beautiful details, would not be reproducible again for the new upscaled image, since adetailer does not have seed as such
