### ISSUE TITLE
HELP ME! [-] ADetailer: Failed to load model 'face_yolov8s.pt' from huggingface

### ISSUE THREAD

**Issue by hucaixue** [Bing-su/adetailer#326]
### Question

What's the problem? Thanks!
---------------------------------------------------

import torch: 2.5s, import gradio: 1.0s, setup paths: 0.7s, initialize shared: 0.2s, other imports: 0.8s, setup codeformer: 0.1s, load scripts: 52.7s, create ui: 1.7s, gradio launch: 2.7s).
Loading VAE weights specified in settings: E:\sd-webui-aki\sd-webui-aki-v4\models\VAE\animevae.pt
Applying attention optimization: xformers... done.
Model loaded in 9.8s (load weights from disk: 0.9s, create model: 0.6s, apply weights to model: 7.1s, load VAE: 0.6s, calculate empty prompt: 0.4s).
Restarting UI...

Closing server running on port: 7860
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Bingsu/adetailer/resolve/main/face_yolov8n.pt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001A8D6E51150>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 2903e6d8-f787-4e95-9871-595fba27b6b9)')' thrown while requesting HEAD https://huggingface.co/Bingsu/adetailer/resolve/main/face_yolov8n.pt

WARNING:huggingface_hub.utils._http:'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Bingsu/adetailer/resolve/main/face_yolov8n.pt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001A8D6E51150>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 2903e6d8-f787-4e95-9871-595fba27b6b9)')' thrown while requesting HEAD https://huggingface.co/Bingsu/adetailer/resolve/main/face_yolov8n.pt
[-] ADetailer: Failed to load model 'face_yolov8n.pt' from huggingface
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Bingsu/adetailer/resolve/main/face_yolov8s.pt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001A8D7398550>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 0a83b5b1-4368-420e-923d-26715b337fba)')' thrown while requesting HEAD https://huggingface.co/Bingsu/adetailer/resolve/main/face_yolov8s.pt

WARNING:huggingface_hub.utils._http:'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Bingsu/adetailer/resolve/main/face_yolov8s.pt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001A8D7398550>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 0a83b5b1-4368-420e-923d-26715b337fba)')' thrown while requesting HEAD https://huggingface.co/Bingsu/adetailer/resolve/main/face_yolov8s.pt
[-] ADetailer: Failed to load model 'face_yolov8s.pt' from huggingface
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Bingsu/adetailer/resolve/main/hand_yolov8n.pt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001A8D739B7C0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 99afabf8-8009-49fc-8cca-c3845c45c5a3)')' thrown while requesting HEAD https://huggingface.co/Bingsu/adetailer/resolve/main/hand_yolov8n.pt

WARNING:huggingface_hub.utils._http:'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Bingsu/adetailer/resolve/main/hand_yolov8n.pt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001A8D739B7C0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 99afabf8-8009-49fc-8cca-c3845c45c5a3)')' thrown while requesting HEAD https://huggingface.co/Bingsu/adetailer/resolve/main/hand_yolov8n.pt
[-] ADetailer: Failed to load model 'hand_yolov8n.pt' from huggingface
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Bingsu/adetailer/resolve/main/person_yolov8n-seg.pt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001A8D7377850>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 57f2a354-bb5b-44a0-b40b-148ac2f2eb20)')' thrown while requesting HEAD https://huggingface.co/Bingsu/adetailer/resolve/main/person_yolov8n-seg.pt

WARNING:huggingface_hub.utils._http:'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Bingsu/adetailer/resolve/main/person_yolov8n-seg.pt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001A8D7377850>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 57f2a354-bb5b-44a0-b40b-148ac2f2eb20)')' thrown while requesting HEAD https://huggingface.co/Bingsu/adetailer/resolve/main/person_yolov8n-seg.pt
[-] ADetailer: Failed to load model 'person_yolov8n-seg.pt' from huggingface
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Bingsu/adetailer/resolve/main/person_yolov8s-seg.pt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001A8D7374A60>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 296264a7-1214-4f54-92bc-32ae5f7e9ac7)')' thrown while requesting HEAD https://huggingface.co/Bingsu/adetailer/resolve/main/person_yolov8s-seg.pt

WARNING:huggingface_hub.utils._http:'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Bingsu/adetailer/resolve/main/person_yolov8s-seg.pt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001A8D7374A60>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 296264a7-1214-4f54-92bc-32ae5f7e9ac7)')' thrown while requesting HEAD https://huggingface.co/Bingsu/adetailer/resolve/main/person_yolov8s-seg.pt
[-] ADetailer: Failed to load model 'person_yolov8s-seg.pt' from huggingface
[-] ADetailer initialized. version: 23.9.2, num models: 4
[AddNet] Updating model hashes...

**Comment by wibur0620** [comment]
In the same situation, when I disable proxy acceleration, it prompts this error. When I enable proxy acceleration, there is no error message.



----------------------------------------------------------------------------------------------------------
venv "D:\AI\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Faceswaplab : Use GPU requirements
Checking faceswaplab requirements
0.017519900000479538
Launching Web UI with arguments: --xformers --no-half-vae --medvram-sdxl
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Bingsu/adetailer/resolve/main/face_yolov8n.pt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000026133428790>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 8fbb09e8-15d1-40fd-b3c2-42729adb7d14)')' thrown while requesting HEAD https://huggingface.co/Bingsu/adetailer/resolve/main/face_yolov8n.pt
WARNING:huggingface_hub.utils._http:'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Bingsu/adetailer/resolve/main/face_yolov8n.pt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000026133428790>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 8fbb09e8-15d1-40fd-b3c2-42729adb7d14)')' thrown while requesting HEAD https://huggingface.co/Bingsu/adetailer/resolve/main/face_yolov8n.pt
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Bingsu/adetailer/resolve/main/face_yolov8s.pt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000026133428CA0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 038975fa-9d68-4d83-b026-1aecf2f059ab)')' thrown while requesting HEAD https://huggingface.co/Bingsu/adetailer/resolve/main/face_yolov8s.pt
WARNING:huggingface_hub.utils._http:'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Bingsu/adetailer/resolve/main/face_yolov8s.pt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000026133428CA0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 038975fa-9d68-4d83-b026-1aecf2f059ab)')' thrown while requesting HEAD https://huggingface.co/Bingsu/adetailer/resolve/main/face_yolov8s.pt
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Bingsu/adetailer/resolve/main/hand_yolov8n.pt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000261334291E0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 08fef55e-59d8-4c9a-84f8-76c878f09bca)')' thrown while requesting HEAD https://huggingface.co/Bingsu/adetailer/resolve/main/hand_yolov8n.pt
WARNING:huggingface_hub.utils._http:'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Bingsu/adetailer/resolve/main/hand_yolov8n.pt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000261334291E0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 08fef55e-59d8-4c9a-84f8-76c878f09bca)')' thrown while requesting HEAD https://huggingface.co/Bingsu/adetailer/resolve/main/hand_yolov8n.pt
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Bingsu/adetailer/resolve/main/person_yolov8n-seg.pt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000026133429810>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 56a3720b-edf2-4ccf-b27a-f3a4b50124b2)')' thrown while requesting HEAD https://huggingface.co/Bingsu/adetailer/resolve/main/person_yolov8n-seg.pt
WARNING:huggingface_hub.utils._http:'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Bingsu/adetailer/resolve/main/person_yolov8n-seg.pt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000026133429810>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 56a3720b-edf2-4ccf-b27a-f3a4b50124b2)')' thrown while requesting HEAD https://huggingface.co/Bingsu/adetailer/resolve/main/person_yolov8n-seg.pt
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Bingsu/adetailer/resolve/main/person_yolov8s-seg.pt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000026133429630>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 3d9e62e9-c798-4715-9761-51e55aa100fb)')' thrown while requesting HEAD https://huggingface.co/Bingsu/adetailer/resolve/main/person_yolov8s-seg.pt
WARNING:huggingface_hub.utils._http:'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Bingsu/adetailer/resolve/main/person_yolov8s-seg.pt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000026133429630>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 3d9e62e9-c798-4715-9761-51e55aa100fb)')' thrown while requesting HEAD https://huggingface.co/Bingsu/adetailer/resolve/main/person_yolov8s-seg.pt
[-] ADetailer initialized. version: 23.9.2, num models: 14
2023-09-14 14:28:18,852 - ControlNet - INFO - ControlNet v1.1.408
ControlNet preprocessor location: D:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-09-14 14:28:19,113 - ControlNet - INFO - ControlNet v1.1.408
sd-webui-prompt-all-in-one background API service started successfully.
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
dirname:  D:\AI\stable-diffusion-webui\localizations
localizations:  {'zh-Hans (Stable) [vladmandic]': 'D:\\AI\\stable-diffusion-webui\\extensions\\界面汉化stable-diffusion-webui-localization-zh_Hans\\localizations\\zh-Hans (Stable) [vladmandic].json', 'zh-Hans (Stable)': 'D:\\AI\\stable-diffusion-webui\\extensions\\界面汉化stable-diffusion-webui-localization-zh_Hans\\localizations\\zh-Hans (Stable).json', 'zh-Hans (Testing) [vladmandic]': 'D:\\AI\\stable-diffusion-webui\\extensions\\界面汉化stable-diffusion-webui-localization-zh_Hans\\localizations\\zh-Hans (Testing) [vladmandic].json', 'zh-Hans (Testing)': 'D:\\AI\\stable-diffusion-webui\\extensions\\界面汉化stable-diffusion-webui-localization-zh_Hans\\localizations\\zh-Hans (Testing).json'}
Loading weights [31e35c80fc] from D:\AI\stable-diffusion-webui\models\Stable-diffusion\sd_xl_base_1.0.safetensors
D:\AI\stable-diffusion-webui\modules\gradio_extensons.py:25: GradioDeprecationWarning: `optional` parameter is deprecated, and it has no effect
  res = original_IOComponent_init(self, *args, **kwargs)
Creating model from config: D:\AI\stable-diffusion-webui\repositories\generative-models\configs\inference\sd_xl_base.yaml
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 84.0s (prepare environment: 7.3s, import torch: 5.0s, import gradio: 1.0s, setup paths: 0.9s, initialize shared: 0.3s, other imports: 0.9s, setup codeformer: 0.1s, load scripts: 58.6s, initialize extra networks: 0.1s, create ui: 4.1s, gradio launch: 3.5s, app_started_callback: 2.0s).
Applying attention optimization: xformers... done.
Model loaded in 19.7s (load weights from disk: 4.2s, create model: 1.5s, apply weights to model: 9.6s, calculate empty prompt: 4.1s).

**Comment by huangyan20** [comment]
Regardless of whether a proxy is used or not, with this error, how can we solve this problem through parameters --ad-no-huggingface? On Windows

**Comment by demaxiya1982** [comment]
我在修改源文件后删除更新动作解决这个问题
路径 extensions\adetailer\adetailer\common.py
修改这个方法 第三行不去下载
def hf_download(file: str):
    try:
        path = "INVALID"
    except Exception:
        msg = f"[-] ADetailer: Failed to load model {file!r} from huggingface"
        print(msg)
        path = "INVALID"
    return path

**Comment by EmmaWebGH** [comment]
Same issue. I already had the model, and after updating Adetailer yesterday now it's trying to connect to HuggingFace site on Auto1111 launch. Why? How to solve please.

**Comment by zhaozhiming** [comment]
> 我在修改源文件后删除更新动作解决这个问题 路径 extensions\adetailer\adetailer\common.py 修改这个方法 第三行不去下载 def hf_download(file: str): try: path = "INVALID" except Exception: msg = f"[-] ADetailer: Failed to load model {file!r} from huggingface" print(msg) path = "INVALID" return path

It works after changing the code.

**Comment by He139836** [comment]
> 我在修改源文件后删除更新动作解决这个问题 路径 extensions\adetailer\adetailer\common.py 修改这个方法 第三行不去下载 def hf_download(file: str): try: path = "INVALID" except Exception: msg = f"[-] ADetailer: Failed to load model {file!r} from huggingface" print(msg) path = "INVALID" return path

it works.

**Comment by LiJT** [comment]
> 我在修改源文件后删除更新动作解决这个问题 路径 extensions\adetailer\adetailer\common.py 修改这个方法 第三行不去下载 def hf_download(file: str): try: path = "INVALID" except Exception: msg = f"[-] ADetailer: Failed to load model {file!r} from huggingface" print(msg) path = "INVALID" return path

it works, the booting speed is much much faster now

**Comment by hben35096** [comment]
It turns out that this is the culprit that causes the slow startup of WebUI!!
